### ISSUE TITLE
64-bit Compatibility

### ISSUE THREAD

**Issue by krawumski** [mobius-looper/mobius#2]
Hello! So now that Claudio has submitted the first pull request, I'm wondering if I should also submit one for my 64-bit build. It will be big but I guess that's what it takes. Any thoughts?

**Comment by ClaudioCas** [comment]
Hi Krawumski,
thanks for your effort! I think you should fork the git repo and push your changes on it first.
Probably we can make a branch for 64bit version.

**Comment by cllunsford** [comment]
I've pushed up my working branch for the 64-bit migration and opened an MR, as well. I'm happy to take edits on that or I can merge my changes into your build if you're feeling confident with the status of your build.

**Comment by ClaudioCas** [comment]
Dear Chris,
thanks a lot for your work! I will try to compile it asap :)!

**Comment by cllunsford** [comment]
There was an error in the deltaFrames function in the version I pushed previously. I've corrected the pointer diff types and pushed a new commit.

**Comment by cllunsford** [comment]
64-bit support has been merged into the master branch. I'll be cutting the 2.5.1 release soon.
