### ISSUE TITLE
Permissions need to be changed for mobius.xml, and ui.xml when using the VST

### ISSUE THREAD

**Issue by emack999** [mobius-looper/mobius#9]
With the app being installed to C:\Program Files,  mobius.xml, and ui,xml get set to read-only. This means that any changes made to the VST version aren't binding once the plugin host is closed.  A workaround is to manually give **Users** Full control , but I think in future builds we'll want those files to give **Users** Full control by default, if possible.

**Comment by cllunsford** [comment]
For an immediate fix, I'll look at using NSIS AccessControl plugin (https://nsis.sourceforge.io/AccessControl_plug-in) to give `Users (S-1-5-32-545)` FullAccess on the mobius.xml and ui.xml files at the time of installation.

I think a better longterm plan is to adopt the AppData convention and put the config files in C:/Users/<user>/AppData/Mobius/ and teach Mobius to prefer the files in this location when present.

**Comment by cllunsford** [comment]
Alright, I have a PR with a change to set the perms on installation. I'm taking a slightly more conservative approach and only setting these perms if the file doesn't already exist (and the installer is creating them). So anyone who has installed the 64-bit build already will need to manually set the permissions or delete/move their config files before running the new installer.  

All users going forward will get the file permissions set to Full on initial installation and they'll be left untouched in subsequent upgrades.
